### ISSUE TITLE
Update static provisioning test to not to use vclib methods

### ISSUE THREAD

**Issue by prashima** [vmware/kubernetes#414] opened 2017-12-06 20:23 UTC
#392 root cause: 
virtualmachine.go#getVirtualDeviceByPath method is making comparison between volume path and disk's backing filename to check if backing file still exists for the given volume. However, the volume path doesn't contain extension .vmdk and if backing filename contains extension .vmdk then the two will not match. As a result detach code moves on assuming that disk is no longer present.

Passed volume path \"[sharedVmfs-1] volumes/myDisk1\"
Backing filename from VM's device list \"[sharedVmfs-1] volumes/myDisk1.vmdk\"

Current tests for static provisioning pass because they make use of same causal method. This prevented detection of the bug via existing tests.

These tests must be updated to make use of gvmomi methods directly to verify disk's presence and not use vclib methods for the same. Thus keeping test and product code separate.

**Comment by prashima** [comment] 2017-12-19 21:45
Team has discussed this issue and agreed upon the priority. This issue should be addressed along with other test automation for project octopus.

Assigning this to @divyenpatel to scope out solution better and to give some time estimate.

**Comment by prashima** [comment] 2017-12-19 22:38
Please note that this doesn't need to go in 1.9.*. We can put along with other test automation for project octopus.

**Comment by divyenpatel** [comment] 2018-01-18 18:37
Duplicate of https://github.com/vmware/kubernetes/issues/434

**Closed by divyenpatel** 2018-01-18 18:37 UTC
Labels: P0, Project Octopus, Tests
