### ISSUE TITLE
Create E2E test branch for 1.7 release

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#330] opened 2017-10-17 23:28 UTC
- [x] Identify what tests can be executed on 1.7 branch.
- [x] Make necessary test code changes to incorporate into e2e tests.
- [x] Update existing Jenkins Build to use this new 1.7 branch

**Comment by divyenpatel** [comment] 2017-10-27 19:53
@shaominchen 

For this issue, on the private branch based on kubernetes/release 1.7 branch, we need to make sure we have following tests.

- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere_volume_vsan_policy.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere_volume_placement.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere_volume_diskformat.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere_volume_fstype.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/pvc_label_selector.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/persistent_volumes-vsphere.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/pv_reclaimpolicy.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/volumes.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere_volume_ops_storm.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere_volume_datastore.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere_volume_cluster_ds.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere_volume_disksize.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere_statefulsets.go

**Comment by shaominchen** [comment] 2017-11-04 04:17
All proposed 3 tasks are done:
1. Identify what tests can be executed on 1.7 branch.
2. Make necessary test code changes to incorporate into e2e tests.
3. Update existing Jenkins Build to use this new 1.7 branch
However, there are still 8/33 test cases failed. The failures seem to be caused by testbed. Divyen and I will investigate further to get them fixed.

**Comment by shaominchen** [comment] 2017-11-04 04:18
The latest jenkins job result: http://cna-storage-jenkins.eng.vmware.com/job/k8s-release-1.7-validation/17/

**Comment by shaominchen** [comment] 2017-11-07 22:13
All proposed test cases (13 test groups / 40 test cases) passed on 1.7 branch: http://cna-storage-jenkins.eng.vmware.com/job/k8s-release-1.7-validation/5/

I'm closing this issue as fixed.

**Closed by shaominchen** 2017-11-07 22:13 UTC

**Comment by shaominchen** [comment] 2017-11-07 22:16
Update the estimate to reflect the real work that we have done - not only just creating the testbed, branch and crossporting test cases, but also did a lot of code change to switch to older k8s APIs and to fix different test issues.
