### ISSUE TITLE
K8s e2e tests configuration for multi-vc

### ISSUE THREAD

**Issue by abrarshivani** [vmware/kubernetes#412] opened 2017-12-05 00:20 UTC
Currently, we accept environment variables for single VC, we need to change to multi-vc.

**Comment by prashima** [comment] 2018-01-02 23:50
@abrarshivani the tests on PR https://github.com/kubernetes/kubernetes/pull/57258 are failing.

**Comment by BaluDontu** [comment] 2018-01-09 23:36
make verify is failing on the kubernetes PR because it found a flag "VCP_STRESS_ITERATIONS" declared with an _ which is not explicitly listed as a valid flag name in hack/verify-flags/excluded-flags.txt.

The problem is with this specific line
Expect(err).NotTo(HaveOccurred(), "Error Parsing VCP_STRESS_ITERATIONS") in vsphere_stress.go file.

where it expects to not have _ as part of NotTo statement. Since this is an environment variable which needs to defined for running vsphere tests, I have explicitly added it to hack/verify-flags/excluded-flags.txt so that verify-flags-underscore.py doesn't complain anymore.

**Comment by BaluDontu** [comment] 2018-01-19 07:18
The PR on kubernetes#57258 is merged. Closing this issue.

**Closed by BaluDontu** 2018-01-19 07:18 UTC
Labels: P0, Project Octopus, Tests, merge pending
