### ISSUE TITLE
Fix node locking to ensure atomic attach operation

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#333] opened 2017-10-18 16:48 UTC
@abrarshivani observed this issue during debugging.

Issue is in the following code.

https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/vsphere_volume/attacher.go#L74
```
// Keeps concurrent attach operations to same host atomic
	attachdetachMutex.LockKey(string(nodeName))
        defer attachdetachMutex.UnlockKey(string(nodeName))
```

Here `string(nodeName)` returns new object, so we are not locking and unlocking same same object.
Without this lock we may see concurrent attach operation on the same node fail. We may see errors in the VC tasks. We may not observe any pod creation failures as kubernets always retries if the operation fails, but this issue should be fixed.

CC: @abrarshivani @tusharnt @pshahzeb @BaluDontu @tusharnt

**Comment by divyenpatel** [comment] 2017-10-23 18:30
@abrarshivani just checked `attachdetachMutex` is of the type `KeyMutex`. 
Here locking is not based on the object, but actual string value of the key. We do not need any change in the code. Let me know if this can be closed.

```
{"log":"I1023 17:55:06.186791       1 keymutex.go:59] UnlockKey(...) called for id \"kubernetes-node2\"\r\n","stream":"stderr","time":"2017-10-23T17:55:06.187613332Z"}
{"log":"I1023 17:55:06.186852       1 keymutex.go:66] UnlockKey(...) for id. Mutex found, trying to unlock it. \"kubernetes-node2\"\r\n","stream":"stderr","time":"2017-10-23T17:55:06.187865278Z"}
```

Executed test to verify attaching 30 volumes to the same node. No issue observed.

```
[sig-storage] Volume Operations Storm [Feature:vsphere]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/framework.go:22
  should create pod with many volumes and verify no attach call fails
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/vsphere_volume_ops_storm.go:91
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSOct 23 11:02:00.434: INFO: Running AfterSuite actions on all node
Oct 23 11:02:00.434: INFO: Running AfterSuite actions on node 1

Ran 1 of 715 Specs in 490.951 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 714 Skipped PASS
```
No issue observed on VC tasks console.
![multi-attach-same-node](https://user-images.githubusercontent.com/22985595/31906212-60dcab4a-b7e5-11e7-81cd-38f6007980c8.png)

**Comment by abrarshivani** [comment] 2017-10-23 19:05
Thanks, @divyenpatel for verifying. I found this warning once, yet not sure what was the cause. Will close this issue.

**Closed by abrarshivani** 2017-10-23 19:05 UTC
Labels: P0
