### ISSUE TITLE
kubernetes incorrectly removes a node sometimes

### ISSUE THREAD

**Issue by casualjim** [vmware/kubernetes#195] opened 2017-06-29 23:28 UTC
**Kubernetes version** (use `kubectl version`):

root@leader [ ~ ]# kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: vsphere
- **OS** (e.g. from /etc/os-release): VMware Photon
- **Kernel** (e.g. `uname -a`): 4.4.71-1.ph1-esx #1-photon 
- **Install tools**:
- **Others**:

**What happened**:

When I bring up a cluster, sometimes (1/20) a node registers itself to then later on be deleted by the cloud provider which then removes the node from kubernetes inventory.

```
Jun 29 20:52:08 leader controller-manager[526]: W0629 20:52:08.416732     526 nodecontroller.go:947] Missing timestamp for Node worker-3. Assuming now as a timestamp.
Jun 29 20:52:08 leader controller-manager[526]: I0629 20:52:08.423143     526 event.go:217] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"worker-1", UID:"d0be4a37-5d0c-11e7-86b7-000c29a77d25", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason:
 'RegisteredNode' Node worker-1 event: Registered Node worker-1 in NodeController
Jun 29 20:52:08 leader controller-manager[526]: I0629 20:52:08.423521     526 event.go:217] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"worker-3", UID:"d0d9bb0c-5d0c-11e7-86b7-000c29a77d25", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason:
 'RegisteredNode' Node worker-3 event: Registered Node worker-3 in NodeController
Jun 29 20:52:08 leader controller-manager[526]: E0629 20:52:08.603912     526 vsphere.go:602] Failed to getVMandMO for ExternalID: err instance not found
```

**Anything else we need to know**:

This is in a nested esxi environment

**Comment by tusharnt** [comment] 2017-06-30 22:46
@casualjim Is this a blocker for KOV or can we punt this to September sprint?
@BaluDontu Since you briefly looked into this please update the issue with you analysis. If it's not a blocker then we can delay the detailed investigation & fix till September sprint.

**Comment by BaluDontu** [comment] 2017-06-30 23:05
The only place where Kubernetes would delete the node from the cloud provider once it is already registered is when node status says the node is NotReady and subsequent query to see if node cannot be found in the cloud provider. Once the node is not found in cloud provider, it would delete it. 

It can be seen here - https://github.com/kubernetes/kubernetes/blob/886e04f1fffbb04faf8a9f9ee141143b2684ae68/pkg/controller/cloud/nodecontroller.go#L241

and a call to vSphere Cloud Provider - https://github.com/kubernetes/kubernetes/blob/v1.6.6/pkg/cloudprovider/providers/vsphere/vsphere.go#L602 failed with cloudprovider.InstanceNotFound.

Based on all this information, the possible reason would be that the Kubelet might have gone down or was unable to communicate its status to the controller manager. Because of this node status went to NotReady.

@casualjim : if possible, can you post the logs for kubelet for Node worker-3. Also a temporary solution would be restart the kubelet to see if the node is registered back to the controller manager.

**Comment by tusharnt** [comment] 2017-07-18 17:47
@casualjim can you please comment?

**Comment by casualjim** [comment] 2017-07-18 19:03
https://github.com/vmware/kov/issues/345

http://sc-dbc1213.eng.vmware.com/famanda/kubelet-log-on-failed-node.txt

We can reproduce this by pushing the vm close to the memory limit, the vm is still there but the cloud provider removes the node.

**Comment by BaluDontu** [comment] 2017-07-19 22:19
The only place when the kubernetes would delete the node is if the following sequence of steps happen.

1. Kubelet is unable to report the node status to controller manager. In this state, the node goes into NodeReady state.
2. Once the node is NotReady remains node ready, the controller manager check with the cloud provider to see if the node still exists in the cloud provider. This is made by calling ExternalID() API on vsphere cloud provider with the node name.
3. In ExternalID(), vsphere cloud provider checks if the node exists on VC. If it is unable to find the node on VC, kubernetes deletes the node from its internal states. So in your case, vsphere cloud provider is unable to find the node "kov-trial-1-worker-0" in VC. I am trying to figure out why this happens even if the node is present on VC.

Based on the offline discussion @casualjim, he confirmed the same sequence of actions that are happening in his environment.

1. Based on logs on kubelet, I could see that there was a request timeout on node "kov-trial-1-worker-0" which eventually led the node to go to NotReady state which confirms point 1 mentioned above.
> Jul 17 23:36:30 kov-trial-1-worker-0 kubelet[780]: E0717 23:36:30.478952     780 kubelet_node_status.go:357] Error updating node status, will retry: error getting node "kov-trial-1-worker-0": Get https://kov-trial-1-leader:6443/api/v1/nodes/kov-trial-1-worker-0?resourceVersion=0: read tcp 10.160.55.245:57094->10.160.55.69:6443: read: connection timed out
> 
> Jul 18 05:38:01 kov-trial-1-worker-0 kubelet[780]: E0718 05:38:01.931683     780 kubelet_node_status.go:357] Error updating node status, will retry: failed to patch status "{\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"OutOfDisk\"},{\"type\":\"MemoryPressure\"},{\"type\":\"DiskPressure\"},{\"type\":\"Ready\"}],\"conditions\":[{\"lastHeartbeatTime\":\"2017-07-18T05:37:54Z\",\"type\":\"OutOfDisk\"},{\"lastHeartbeatTime\":\"2017-07-18T05:37:54Z\",\"type\":\"MemoryPressure\"},{\"lastHeartbeatTime\":\"2017-07-18T05:37:54Z\",\"type\":\"DiskPressure\"},{\"lastHeartbeatTime\":\"2017-07-18T05:37:54Z\",\"type\":\"Ready\"}]}}" for node "kov-trial-1-worker-0": etcdserver: request timed out

2. vsphere cloud provider is unable to find the node "kov-trial-1-worker-0" in VC which led to the eventual deletion of the node from kubernetes cluster. 
From the vsphere.conf mentioned below, vsphere cloud provider searches for node "kov-trial-1-worker-0" at working directory - " /var/srv/vsphere" location. From discussion with @casualjim , it seems that its not the location where VM is residing on vCenter. Hence vsphere cloud provider failed to get the node on VC that eventually led to node deletion in kubernetes cluster.
root@kov-demo-leader [ ~ ]# cat /etc/vsphere/vsphere.conf 
[Global]
  user = "administrator@vsphere.local"
  password = "Admin!23"
  server = "10.160.53.204"
  insecure-flag = 1
  datacenter = "vicdc"
  datastore = "nfs0-1"
  working-dir = /var/srv/vsphere
[Disk]
  scsicontrollertype = pvscsi
The fix for this would be to specify the right working-directory path and try the same scenario again. 

@casualjim to try this and will provide the feedback.

**Comment by tusharnt** [comment] 2017-07-27 21:09
@casualjim Does the solution suggested by @BaluDontu work? We would to close this issue if it does.

**Comment by tusharnt** [comment] 2017-08-09 00:17
Closing this since there are no product issues here.

**Closed by tusharnt** 2017-08-09 00:17 UTC
Labels: customer, P0
