### ISSUE TITLE
Project Octopus: Detached failed in static provisioned volume

### ISSUE THREAD

**Issue by abrarshivani** [vmware/kubernetes#392] opened 2017-11-21 21:17 UTC
Manual Test Done:

1. Provisioned volume statically.
2. Created Pod using the volume.
3. Deleted pod.

Observations:
1. Volume was attached successfully and pod was running.
2. Volume was not detached from node yet k8s reported volume detached successfully.

Log:
```
{"log":"I1121 20:53:54.523702       1 operation_generator.go:740] Verified volume is safe to detach for volume \"test-volume\" (UniqueName: \"kubernetes.io/vsphere-volume/[sharedVmfs-0] myDisk1\") on node \"kubernetes-node2\" \n","stream":"stderr","time":"2017-11-21T20:53:54.523770733Z"}
{"log":"I1121 20:53:54.535397       1 attacher.go:267] detach operation was successful. volume \"[sharedVmfs-0] myDisk1\" is already detached from node \"kubernetes-node2\".\n","stream":"stderr","time":"2017-11-21T20:53:54.535509134Z"}
{"log":"I1121 20:53:54.535584       1 operation_generator.go:368] DetachVolume.Detach succeeded for volume \"test-volume\" (UniqueName: \"kubernetes.io/vsphere-volume/[sharedVmfs-0] myDisk1\") on node \"kubernetes-node2\" \n","stream":"stderr","time":"2017-11-21T20:53:54.535602507Z"}
```

**Comment by prashima** [comment] 2017-12-06 19:49
This bug exists in 1.8 version as well and needs to be cherry-picked.

**Comment by prashima** [comment] 2017-12-06 20:20
Root cause: 
virtualmachine.go#getVirtualDeviceByPath method is making comparison between volume path and disk's backing filename to check if backing file still exists for the given volume. However, the volume path doesn't contain extension .vmdk and if backing filename contains extension .vmdk then the two will not match. As a result detach code with move on assuming that disk is no longer present.

Passed volume path \"[sharedVmfs-1] volumes/myDisk1\"
Backing filename from VM's device list \"[sharedVmfs-1] volumes/myDisk1.vmdk\"

Current tests for static provisioning pass because they make use of same causal method. This prevented detection of the bug via existing tests.

**Comment by prashima** [comment] 2017-12-07 19:47
Update on root cause:

The real root cause of this problem is the fact that VCP allows volume creation even when volume path doesn't contain .vmdk extension and disk does. This leads to the problem at the time of detach. However, we can't fix auto appending of .vmdk to volume path that misses it, because that happens in gvmomi code. If we try to change this behavior in govmomi we might break other people's code. So we fix it at detach time.

**Comment by prashima** [comment] 2017-12-18 19:41
PR is merged. Closing this issue. 

Opened new issue to track cherry picking https://github.com/vmware/kubernetes/issues/420

**Closed by prashima** 2017-12-18 19:41 UTC
Labels: bug, P0, Project Octopus
