### ISSUE TITLE
Project Octopus: Fail to provision volume dynamically with error NotAuthorized

### ISSUE THREAD

**Issue by abrarshivani** [vmware/kubernetes#393] opened 2017-11-21 22:01 UTC
Manually Tested:
1. Created Storage Class
2. Created PVC with storage class.

Observation:
Failed to provision vSphere volume.

Log:
```
{"log":"I1121 21:34:05.482949       1 vsphere.go:1001] Starting to create a vSphere volume with volumeOptions: \u0026{CapacityKB:2097152 Tags:map[kubernetes.io/created-for/pvc/namespace:default kubernetes.io/created-for/pvc/name:pvcsc-vsan kubernetes.io/created-for/pv/name:pvc-b31478fe-cf03-11e7-9e58-00505683801a] Name:kubernetes-dynamic-pvc-b31478fe-cf03-11e7-9e58-00505683801a DiskFormat: Datastore: VSANStorageProfileData: StoragePolicyName: StoragePolicyID: SCSIControllerType:}\n","stream":"stderr","time":"2017-11-21T21:34:05.48342674Z"}
{"log":"W1121 21:34:05.492369       1 connection.go:71] Creating new client session since the existing session is not valid or not authenticated\n","stream":"stderr","time":"2017-11-21T21:34:05.492443582Z"}
{"log":"I1121 21:34:05.558281       1 vsphere_util.go:198] Getting accessible datastores for node kubernetes-node1\n","stream":"stderr","time":"2017-11-21T21:34:05.558416714Z"}
{"log":"E1121 21:34:05.564651       1 virtualmachine.go:207] Failed to get host system for VM: \"\". err: NotAuthenticated\n","stream":"stderr","time":"2017-11-21T21:34:05.564715046Z"}
{"log":"I1121 21:34:05.564801       1 vsphere_util.go:181] error \"NotAuthenticated\" getting accessible datastores for node \u0026{NodeName:kubernetes-node1 vm:0xc42017ddc0}\n","stream":"stderr","time":"2017-11-21T21:34:05.564991059Z"}
{"log":"E1121 21:34:05.565018       1 vsphere.go:1053] Failed to get shared datastore: NotAuthenticated\n","stream":"stderr","time":"2017-11-21T21:34:05.565091053Z"}
{"log":"I1121 21:34:05.565199       1 vsphere.go:1105] The canonical volume path for the newly created vSphere volume is \"\"\n","stream":"stderr","time":"2017-11-21T21:34:05.56521824Z"}
{"log":"I1121 21:34:05.565309       1 pv_controller.go:1317] failed to provision volume for claim \"default/pvcsc-vsan\" with StorageClass \"fast\": NotAuthenticated\n","stream":"stderr","time":"2017-11-21T21:34:05.565348554Z"}
{"log":"I1121 21:34:05.565580       1 event.go:218] Event(v1.ObjectReference{Kind:\"PersistentVolumeClaim\", Namespace:\"default\", Name:\"pvcsc-vsan\", UID:\"b31478fe-cf03-11e7-9e58-00505683801a\", APIVersion:\"v1\", ResourceVersion:\"51153\", FieldPath:\"\"}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass \"fast\": NotAuthenticated\n","stream":"stderr","time":"2017-11-21T21:34:05.565622914Z"}
{"log":"I1121 21:34:05.565199       1 vsphere.go:1105] The canonical volume path for the newly created vSphere volume is \"\"\n","stream":"stderr","time":"2017-11-21T21:34:05.56521824Z"}
{"log":"I1121 21:34:05.565309       1 pv_controller.go:1317] failed to provision volume for claim \"default/pvcsc-vsan\" with StorageClass \"fast\": NotAuthenticated\n","stream":"stderr","time":"2017-11-21T21:34:05.565348554Z"}
{"log":"I1121 21:34:05.565580       1 event.go:218] Event(v1.ObjectReference{Kind:\"PersistentVolumeClaim\", Namespace:\"default\", Name:\"pvcsc-vsan\", UID:\"b31478fe-cf03-11e7-9e58-00505683801a\", APIVersion:\"v1\", ResourceVersion:\"51153\", FieldPath:\"\"}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass \"fast\": NotAuthenticated\n","stream":"stderr","time":"2017-11-21T21:34:05.565622914Z"}
```

Cause:
While creating volume we get all accessible datastores for getting datastores which are shared between all k8s vms. While getting shared datastore we execute calls to VCs where the VMs are present to get datastores accessible to the VMs. Since we are not renewing sessions for all those VC's we get Not Authorized Error.

**Note:**
This will occur only when the session is expired.

**Comment by prashima** [comment] 2018-01-02 23:55
Duplicate of  #404

**Closed by prashima** 2018-01-02 23:55 UTC
Labels: bug, duplicate, P0, Project Octopus
